version: '2'
services:
  nginx:
    build: .
    ports:
      - '8443:443'
  keycloak:
    image: 'jboss/keycloak:4.3.0.Final'
    environment:
      - KEYCLOAK_PASSWORD=keycloak
      - KEYCLOAK_USER=keycloak
      - PROXY_ADDRESS_FORWARDING=true
